package System;


import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.WindowConstants;
import javax.swing.table.TableModel;
import models.ComboItem;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author David
 */
public class TeachersMenu extends DBConnection{
    

    /**
     * Creates new form TeachersMenu
     */
    ImageIcon icon;
    
    private String adviserName;
    String Selectedid = "";
    

    
    public TeachersMenu() {
        initComponents();
        Module.AddSection(sectionCmbox);
        Module.AddStudents(studentCmbox);
        Module.AddSubjects(subjectCmbox);
        setIcon();
    }
    
     public void setIcon(){
         icon = new ImageIcon("Images/TitleIcon.png");
         setIconImage(icon.getImage());
         
         //setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("TitleIcon.png")));
     }
    
       public void saveGrades(){
            
            try{    
               
                System.out.println("Successfull get the input");
                     Connection connection = new DBConnection().getConnection();
                     String query ="Insert Into StudentsGrade()";
                     pst = conn.prepareStatement(query);
                     pst.execute();
                   
                   
                    JOptionPane.showMessageDialog(null, "Saved!");
                 
                    } catch (Exception e) {
                      e.printStackTrace();
                          System.out.println(e.getCause());
                              JOptionPane.showMessageDialog(null, e);
                  }
                 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoutBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        firstTxtFld = new javax.swing.JTextField();
        second1TxtFld = new javax.swing.JTextField();
        finalTxtFld = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        studentCmbox = new javax.swing.JComboBox();
        sectionCmbox = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        subjectCmbox = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        sectionTxtFld = new javax.swing.JTextField();
        addSectionBtn = new javax.swing.JButton();
        readBtn = new javax.swing.JButton();
        create = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        subjectTxtFld = new javax.swing.JTextField();
        addSubjectBtn = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        sectionSubId = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        addStudentBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        studentSectionIdTxtFld = new javax.swing.JTextField();
        studentNameTxtFld = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        gradingTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        gradeAndSectionCBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        advisersNameTB = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logoutBtn.setText("Log Out");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        second1TxtFld.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                second1TxtFldKeyReleased(evt);
            }
        });

        finalTxtFld.setEditable(false);
        finalTxtFld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("1stQ");

        jLabel13.setText("2ndQ");

        jLabel14.setText("Final");

        studentCmbox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                studentCmboxItemStateChanged(evt);
            }
        });

        sectionCmbox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sectionCmboxItemStateChanged(evt);
            }
        });

        jLabel20.setText("Student Name:");

        jLabel21.setText("Section:");

        jLabel22.setText("Subject:");

        subjectCmbox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                subjectCmboxItemStateChanged(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("ADD THE GRADES OF YOUR STUDENTS:");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("ADD NEW SECTION:");

        jLabel15.setText("Add Section");

        addSectionBtn.setText("Add Section");
        addSectionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSectionBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(87, 87, 87))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sectionTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addSectionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(sectionTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addSectionBtn))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        readBtn.setText("Read");
        readBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readBtnActionPerformed(evt);
            }
        });

        create.setText("Create");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        addSubjectBtn.setText("Add Subject");
        addSubjectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSubjectBtnActionPerformed(evt);
            }
        });

        jLabel18.setText("Section ID:");

        jLabel16.setText("Add Subject");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setText("ADD NEW SUBJECTS:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(subjectTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(sectionSubId, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addSubjectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(subjectTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(sectionSubId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addSubjectBtn))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel19.setText("Section ID:");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("ADD A STUDENT:");

        addStudentBtn.setText("Add Student");
        addStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentBtnActionPerformed(evt);
            }
        });

        jLabel12.setText("Student's Name:");

        studentSectionIdTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentSectionIdTxtFldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentNameTxtFld)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(studentSectionIdTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addStudentBtn))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentNameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addStudentBtn)
                    .addComponent(jLabel19)
                    .addComponent(studentSectionIdTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel20)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(studentCmbox, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sectionCmbox, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(subjectCmbox, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(firstTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel13)
                                        .addGap(0, 0, 0)
                                        .addComponent(second1TxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel14)
                                        .addGap(14, 14, 14)
                                        .addComponent(finalTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(updateBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(create)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(readBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(deleteBtn)))))
                        .addGap(221, 221, 221))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sectionCmbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentCmbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjectCmbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finalTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(second1TxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(readBtn)
                    .addComponent(create)
                    .addComponent(updateBtn)
                    .addComponent(deleteBtn))
                .addGap(51, 51, 51))
        );

        gradingTable.setAutoCreateRowSorter(true);
        gradingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Student Name", "1st", "2nd", "Final", "1st", "2nd", "Final", "1st", "2nd", "Final", "1st", "2nd", "Final", "1st", "2nd", "Final", "1st", "2nd", "Final", "1st", "2nd", "Final", "GenAve"
            }
        ));
        gradingTable.setDragEnabled(true);
        gradingTable.setSurrendersFocusOnKeystroke(true);
        gradingTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gradingTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(gradingTable);
        if (gradingTable.getColumnModel().getColumnCount() > 0) {
            gradingTable.getColumnModel().getColumn(0).setPreferredWidth(400);
        }

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));

        gradeAndSectionCBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                gradeAndSectionCBoxItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Grade and Section");

        jLabel1.setText("Teachers Name:");

        advisersNameTB.setEditable(false);
        advisersNameTB.setBorder(null);
        advisersNameTB.setOpaque(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(advisersNameTB))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(16, 16, 16)
                        .addComponent(gradeAndSectionCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(advisersNameTB, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(gradeAndSectionCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 867, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        setBounds(0, 0, 1308, 710);
    }// </editor-fold>//GEN-END:initComponents

    private void gradeAndSectionCBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_gradeAndSectionCBoxItemStateChanged
        
        Object comboItem = gradeAndSectionCBox.getSelectedItem();
        int state = evt.getStateChange();
        if(comboItem != null && state == ItemEvent.SELECTED){
            String key = ((ComboItem) comboItem).getKey();
            Module.getStudentsGrade(key, gradingTable);
        }
        
    }//GEN-LAST:event_gradeAndSectionCBoxItemStateChanged

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        Module.teacherslogin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void gradingTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gradingTableMouseClicked
//    Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
//    Module.card.getContentPane().removeAll();
//    Module.card.setSize(300, 600);
//    Module.card.validate();
//    Module.card.repaint(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2, 600,600);
    int index = gradingTable.getSelectedRow();
    TableModel model = gradingTable.getModel();
    
    System.out.println(sectionCmbox.getSelectedItem());
    String studentName = model.getValueAt(index,0).toString();
    Module.card = new Card();
    Module.card.setStudentsName(studentName);
    int yCount = 0;
    int xCount = 0;
        System.out.println(Module.getStudentsGradeCount);
    for (int i = 1; i < Module.getStudentsGradeCount; i++) {
        System.out.println(model.getValueAt(index,i));
        
        // SET SUBJECT
        JTextField field = new JTextField(20);
        field.setBounds(20, (100+yCount), 100, 25);
        field.setText(model.getValueAt(index,i++).toString());
        Module.card.add(field);
        
        // SET FIRST QUARTER
        field = new JTextField(20);
        field.setBounds(120, (100+yCount), 40, 25);
        field.setText(model.getValueAt(index,i++).toString());
        Module.card.add(field);
        
        // SET SECOND QUARTER
        field = new JTextField(20);
        field.setBounds(160, (100+yCount), 40, 25);
        field.setText(model.getValueAt(index,i++).toString());
        Module.card.add(field);
        
        // SET FINAL
        field = new JTextField(20);
        field.setBounds(200, (100+yCount), 40, 25);
        field.setText(model.getValueAt(index,i).toString());
        Module.card.add(field);
        
        // STATUS
        field = new JTextField(20);
        field.setBounds(240, (100+yCount), 100, 25);
        field.setText((Integer.parseInt(model.getValueAt(index,i).toString()) > 75  ? "PASSED" : "FAILED"));
        Module.card.add(field);
        
        yCount+=30;

    }

//    String firstSub1 = model.getValueAt(index,2).toString();
//    String secondSub1 = model.getValueAt(index,3).toString();
//    String final1 = model.getValueAt(index,4).toString();
//    String sub1 = model.getValueAt(index,1).toString();
//    String firstSub2 = model.getValueAt(index,6).toString();
//    String secondSub2 = model.getValueAt(index,7).toString();
//    String sub2 = model.getValueAt(index,5).toString();
//    String final2 = model.getValueAt(index,8).toString();
//    String firstSub3 = model.getValueAt(index,10).toString();
//    String secondSub3 = model.getValueAt(index,11).toString();
//    String final3 = model.getValueAt(index,12).toString();
//    String sub3 = model.getValueAt(index,9).toString();
//    String sub4 = model.getValueAt(index,13).toString();
//    String firstSub4 = model.getValueAt(index,14).toString();
//    String secondSub4 = model.getValueAt(index,15).toString();
//    String final4 = model.getValueAt(index,16).toString();
////    String sub5 = model.getValueAt(index,17).toString();
////    String firstSub5= model.getValueAt(index,18).toString();
////    String secondSub5 = model.getValueAt(index,19).toString();
////    String final5 = model.getValueAt(index,20).toString();
////    String sub6 = model.getValueAt(index,21).toString();
////    String firstSub6 = model.getValueAt(index,22).toString();
////    String secondSub6 = model.getValueAt(index,23).toString();
////    String final6 = model.getValueAt(index,24).toString();
////    String sub7 = model.getValueAt(index,25).toString();
////    String firstSub7 = model.getValueAt(index,26).toString();
////    String secondSub7 = model.getValueAt(index,27).toString();
////    String final7 = model.getValueAt(index,28).toString();
//    
    
    Module.card.setVisible(true);
    Module.card.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    
//    Module.card.studentNameTxtFld.setText(studentName);
//    Module.card.firstSub1TxtFld.setText(firstSub1);
//    Module.card.secondSub1TxtFld1.setText(secondSub1);
//    Module.card.final1TxtFld1.setText(final1);
//    Module.card.firstSub2TxtFld1.setText(firstSub2);
//    Module.card.secondSub2TxtFld1.setText(secondSub2);
//    Module.card.final2TxtFld.setText(final2);
//    Module.card.firstSub3TxtFld1.setText(firstSub3);
//    Module.card.secondSub3TxtFld1.setText(secondSub3);
//    Module.card.final3TxtFld.setText(final3);
//    Module.card.firstSub4TxtFld1.setText(firstSub4);
//    Module.card.secondSub4TxtFld1.setText(secondSub4);
//    Module.card.final4TxtFld.setText(final4);
////    crd.firstSub5TxtFld1.setText(firstSub5);
////    crd.secondSub5TxtFld1.setText(secondSub5);
////    crd.final5TxtFld.setText(final5);
////    crd.firstSub6TxtFld1.setText(firstSub6);
////    crd.secondSub6TxtFld.setText(secondSub6);
////    crd.final6TxtFld.setText(final6);
////    crd.firstSub7TxtFld1.setText(firstSub7);
////    crd.secondSub7TxtFld.setText(secondSub7);
////    crd.final7TxtFld.setText(final7);
//      Module.card.subject1.setText(sub1);
//      Module.card.subject2.setText(sub2);
//      Module.card.subject3.setText(sub3);
//      Module.card.subject4.setText(sub4);
////    crd.subject5.setText(sub5);
////    crd.subject6.setText(sub6);
////    crd.subject7.setText(sub7);
//      
//      if(Integer.parseInt(final1) >= 75 ){
//         Module.card.remarks1TxtFld.setText("Passed");
//     }else{
//         Module.card.remarks1TxtFld.setText("Failed");
//     }
//      if(Integer.parseInt(final2) >= 75 ){
//         Module.card.remarks2TxtFld.setText("Passed");
//     }else{
//         Module.card.remarks2TxtFld.setText("Failed");
//     }
//      if(Integer.parseInt(final3) >= 75 ){
//         Module.card.remarks3TxtFld.setText("Passed");
//     }else{
//         Module.card.remarks3TxtFld.setText("Failed");
//     }
//      if(Integer.parseInt(final4) >= 75 ){
//         Module.card.remark4TxtFld.setText("Passed");
//     }else{
//         Module.card.remark4TxtFld.setText("Failed");
//     }
////      if(Integer.parseInt(final) >= 75 ){
////         crd.remarks5TxtFld.setText("Passed");
////     }else{
////         crd.remarks5TxtFld.setText("Failed");
//     }
    }//GEN-LAST:event_gradingTableMouseClicked

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        Module.deleteStudents(studentCmbox.getSelectedItem().toString());     
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        
    }//GEN-LAST:event_updateBtnActionPerformed

    private void addStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentBtnActionPerformed
        Module.saveStudents(studentNameTxtFld.getText(),studentSectionIdTxtFld.getText());
        studentNameTxtFld.setText("");
        studentSectionIdTxtFld.setText("");
    }//GEN-LAST:event_addStudentBtnActionPerformed

    private void addSubjectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSubjectBtnActionPerformed
        Module.saveSubject(subjectTxtFld.getText(),sectionSubId.getText());
        subjectTxtFld.setText("");
        sectionSubId.setText("");
    }//GEN-LAST:event_addSubjectBtnActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        
    }//GEN-LAST:event_createActionPerformed

    private void readBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readBtnActionPerformed

    }//GEN-LAST:event_readBtnActionPerformed

    private void addSectionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSectionBtnActionPerformed

        Module.saveSection(sectionTxtFld.getText());
        sectionTxtFld.setText("");
        
    }//GEN-LAST:event_addSectionBtnActionPerformed

    private void subjectCmboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_subjectCmboxItemStateChanged

        Object comboItem = subjectCmbox.getSelectedItem();
        int state = evt.getStateChange();
        if(comboItem != null && state == ItemEvent.SELECTED){
            String key = ((ComboItem) comboItem).getKey();
        }

    }//GEN-LAST:event_subjectCmboxItemStateChanged

    private void sectionCmboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sectionCmboxItemStateChanged

        Object comboItem = sectionCmbox.getSelectedItem();
        int state = evt.getStateChange();
        if(comboItem != null && state == ItemEvent.SELECTED){
            String key = ((ComboItem) comboItem).getKey();
        }
    }//GEN-LAST:event_sectionCmboxItemStateChanged

    private void studentCmboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_studentCmboxItemStateChanged

        Object comboItem = studentCmbox.getSelectedItem();
        int state = evt.getStateChange();
        if(comboItem != null && state == ItemEvent.SELECTED){
            String key = ((ComboItem) comboItem).getKey();
        }

    }//GEN-LAST:event_studentCmboxItemStateChanged

    private void second1TxtFldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_second1TxtFldKeyReleased
        int first=Integer.parseInt(firstTxtFld.getText());
        int second =Integer.parseInt(second1TxtFld.getText());
        String final1 =Integer.toString((first + second) /2);
        finalTxtFld.setText(final1);
    }//GEN-LAST:event_second1TxtFldKeyReleased

    private void studentSectionIdTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentSectionIdTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentSectionIdTxtFldActionPerformed

    public void refreshSection(){
        Module.JCBox(gradeAndSectionCBox);
    }
    
    public void setAdviserName(String adviserName) {
        advisersNameTB.setText(adviserName);
        this.adviserName = adviserName;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeachersMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeachersMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeachersMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeachersMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeachersMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSectionBtn;
    private javax.swing.JButton addStudentBtn;
    private javax.swing.JButton addSubjectBtn;
    private javax.swing.JTextField advisersNameTB;
    private javax.swing.JButton create;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField finalTxtFld;
    private javax.swing.JTextField firstTxtFld;
    private javax.swing.JComboBox gradeAndSectionCBox;
    private javax.swing.JTable gradingTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton readBtn;
    private javax.swing.JTextField second1TxtFld;
    private javax.swing.JComboBox sectionCmbox;
    public static javax.swing.JTextField sectionSubId;
    public static javax.swing.JTextField sectionTxtFld;
    private javax.swing.JComboBox studentCmbox;
    public javax.swing.JTextField studentNameTxtFld;
    private javax.swing.JTextField studentSectionIdTxtFld;
    private javax.swing.JComboBox subjectCmbox;
    public static javax.swing.JTextField subjectTxtFld;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
